version: '2.1'

volumes:
    sense-data:
    dashboard-data:
services:
  influxdb:
    restart: always
    image: arm32v7/influxdb@sha256:2fed9b09a672cab330ac3ea1f03616e6821f2235bda64d549f605ef0d7081911
    volumes:
      - 'sense-data:/var/lib/influxdb'
  dashboard:
    image: balenablocks/dashboard
    restart: always
    volumes:
        - 'dashboard-data:/data'
    ports:
        - '80'
  scale:
    image: bh.cr/olamide_omolola/scales
    restart: always
    privileged: true
    labels:
      io.balena.features.kernel-modules: '1'
      io.balena.features.sysfs: '1'
      io.balena.features.supervisor-api: '1'
    #environment: # You can set the calibrated value of the load cell here or on the dashboard
    #  - CALIBRATION_VALUE=-254.1
    #expose:
    #  - '7575'
  connector:
    image: balenablocks/connector
    restart: always
    labels:
      io.balena.features.balena-api: '1'
      io.balena.features.supervisor-api: '1'
    privileged: true
  mqtt:
    image: eclipse-mosquitto:1.6.15
    ports:
      - "1883:1883"
    restart: always  
