version: '2.1'

services:
  connector:
    image: bh.cr/balenablocks/connector-aarch64
    restart: always
    labels:
      io.balena.features.balena-api: '1' # necessary to discover services
      io.balena.features.supervisor-api: 1  # necessary to discover services in local mode
    privileged: true # necessary to change container hostname
    # ports:
      #- "8080" # only necessary if using ExternalHttpListener (see below)
  mqtt:
    image: arm32v6/eclipse-mosquitto
    ports:
      - "1883:1883"
    restart: always
  scale:
    image: bh.cr/balenablocks/scale-aarch64
    privileged: true
    network_mode: host

